#141 【フロント】contactページデザイン
nina-dev/dev pull request #172
Opened 2017-08-06 17:04 UTC by onishi-nina

「c-form.js」と「_form.scss」のコンフリクトを解消したコミットです。

2017-08-06 18:13 UTC, nina-fujioka requested changes
全般的にjsに記述しているelementのパスは古いのでsqlの確認を。もし、sqlが更新されてない場合は共有くださいー

2017-08-06 18:13 UTC, nina-fujioka commented on resource/assets/js/c-form.js
> +    $('button').wrap('<li class="p-form__btn__item c-cta__inner__btn c-btn--secondary--orange"></div>');
ごめん、これもう一度sqlを読み込んで確認を。。  
sqlがぶつかってなければ、不要なdiv削除とbem構成に修正・変更しているはず。

あと、p-form__btn__item **c-cta__inner__btn** c-btn--secondary--orange <--このc-cta__inner__btn?  
確かに1カラム時代のclassには付与して前のタグを使用してもOKではあるのだけど、、今は２カラムで不要クラスであるのでは明確なので削除。 (ここも即出で修正してコミット済)

2017-08-06 18:13 UTC, nina-fujioka commented on resource/assets/js/c-form.js
> +    $('.c-form').each(function() {
ここも、上と同じでsqlがぶつかってなければ、bemに沿ってパスが変更しているはず。  
それか俺がコミットし忘れているか。。

2017-08-06 18:13 UTC, nina-fujioka commented on resource/assets/js/c-form.js
> +        $(this).find('.c-form--text').focus(function(){
ここも同様。 おそらく新しいsqlだとjs記述が読まれていないはず。

2017-08-06 18:13 UTC, nina-fujioka commented on resource/assets/sass/object/project/_form.scss
> +.p-form__btn {
ここはおそらく問題なし。

2017-08-06 19:26 UTC, onishi-nina commented
以下のコミットで「c-form.js」を書き換えていますので、ご確認をお願い致します。
https://github.com/nina-dev/dev/pull/172/commits/2f16047e3b357a3f2f192cf221a99881f05f101b #141 c-form.jsと_form.scssのコンフリクトを解消

▼対応した内容
以下のクラス名を書き換えました。
c-form--text
→ c-form__text

c-form--sampletext
→ c-form__sampletext

c-form--sampletext--show
→ c-form__sampletext--show

c-form--attention
→ c-form__attention

c-form--attention--show
→ c-form__attention--show

※sqlファイルは https://github.com/nina-dev/dev/commit/fd8631efd7507974c607bf4c43fd224c8eb468f7 のコミット分のを再読込しました。
js記述が読まれていないのも確認したので対応します！

2017-08-07 08:38 UTC, nina-fujioka commented
了解です！ちょっと確認してみます。

2017-08-07 08:38 UTC, merged